account:
  username: Replace with your actual username
  password: Replace with your actual password
  # ^ 
  # | Put your account username and password here
messages:
  - Hiiii im a girl, join my discord server at discord,gg/robtopgames {random}
  - UwU i will kiss u if u join discord,gg/robtopgames (nyaaa~ im a girl btw) {random}
  - I love ppl who join discord,gg/robtopgames so much (im a girl btw) {random}
  # - This is a test message
  # You can add as many messages as u want
  # Pro tip: {random} will be replaced with random characters to prevent being detected easily

random_length: 5
# How many random characters should be added to the message in {random}

comment_upload_delay: 30
# Delay in seconds between comment uploads, don't go under 25 with a single IP

percentage: 0
# Percentage of completion displayed on the comment, set it to 0 if you don't want it to be displayed, don't set to above 100